/**
 * 헤더/검색/CTA 계측용 이벤트명·소스 상수.
 * 이후 PR에서 공통으로 사용할 이름을 고정한다.
 */

import type { AnalyticsEventName, AnalyticsSource } from "./types";

/** 이벤트명 상수 */
export const ANALYTICS_EVENTS: Record<AnalyticsEventName, AnalyticsEventName> = {
  header_nav_click: "header_nav_click",
  mega_menu_open: "mega_menu_open",
  mega_menu_click: "mega_menu_click",
  mobile_menu_open: "mobile_menu_open",
  mobile_menu_expand: "mobile_menu_expand",
  mobile_menu_click: "mobile_menu_click",
  search_submit: "search_submit",
  search_suggestion_click: "search_suggestion_click",
  search_recent_click: "search_recent_click",
  search_recommended_click: "search_recommended_click",
  search_result_click: "search_result_click",
  search_no_result: "search_no_result",
  search_filter_change: "search_filter_change",
  search_sort_change: "search_sort_change",
  search_relevance_sort: "search_relevance_sort",
  search_pagination_click: "search_pagination_click",
  search_recommendation_impression: "search_recommendation_impression",
  search_recommendation_click: "search_recommendation_click",
  search_load_more_click: "search_load_more_click",
  hero_search: "hero_search",
  hero_search_submit: "hero_search_submit",
  hero_autosuggest_impression: "hero_autosuggest_impression",
  hero_autosuggest_click: "hero_autosuggest_click",
  cta_click: "cta_click",
  landing_view: "landing_view",
  landing_section_view: "landing_section_view",
  landing_product_click: "landing_product_click",
  product_card_click: "product_card_click",
  product_detail_cta_click: "product_detail_cta_click",
  product_detail_view_summary: "product_detail_view_summary",
  product_itinerary_day_click: "product_itinerary_day_click",
  product_itinerary_image_open: "product_itinerary_image_open",
  product_itinerary_cta_click: "product_itinerary_cta_click",
  product_cta_click: "product_cta_click",
  quote_page_view: "quote_page_view",
  quote_view: "quote_view",
  quote_submit: "quote_submit",
  quote_submit_click: "quote_submit_click",
  quote_submit_success: "quote_submit_success",
  landing_cta_click: "landing_cta_click",
  consult_open: "consult_open",
  consult_submit: "consult_submit",
  deposit_link_click: "deposit_link_click",
  deposit_payment_click: "deposit_payment_click",
  kakao_oauth_start: "kakao_oauth_start",
  kakao_oauth_success: "kakao_oauth_success",
  kakao_signup_new: "kakao_signup_new",
  kakao_login_returning: "kakao_login_returning",
  kakao_oauth_failed: "kakao_oauth_failed",
  home_quick_action_click: "home_quick_action_click",
  home_section_more_click: "home_section_more_click",
  home_promo_impression: "home_promo_impression",
  home_promo_click: "home_promo_click",
  home_promo_dismiss: "home_promo_dismiss",
  home_golf_schedule_click: "home_golf_schedule_click",
  auth_modal_open: "auth_modal_open",
  auth_kakao_cta_click: "auth_kakao_cta_click",
  auth_identifier_continue: "auth_identifier_continue",
  auth_signup_success: "auth_signup_success",
  auth_login_success: "auth_login_success",
  membership_benefit_cta_click: "membership_benefit_cta_click",
  checkout_open: "checkout_open",
  checkout_submit: "checkout_submit",
  checkout_payment_result: "checkout_payment_result",
  order_success_view: "order_success_view",
  payment_return_view: "payment_return_view",
  payment_return_failed: "payment_return_failed",
  planner_landing_view: "planner_landing_view",
  planner_started: "planner_started",
  planner_input_completed: "planner_input_completed",
  planner_generation_started: "planner_generation_started",
  planner_plan_generated: "planner_plan_generated",
  planner_generation_failed: "planner_generation_failed",
  planner_save_clicked: "planner_save_clicked",
  planner_kakao_login_started: "planner_kakao_login_started",
  planner_saved: "planner_saved",
  planner_saved_list_viewed: "planner_saved_list_viewed",
  planner_saved_plan_opened: "planner_saved_plan_opened",
  planner_edit_started: "planner_edit_started",
  planner_edit_succeeded: "planner_edit_succeeded",
  planner_edit_failed: "planner_edit_failed",
} as const;

/** 소스 상수 (enum 성격) */
export const ANALYTICS_SOURCES: Record<AnalyticsSource, AnalyticsSource> = {
  header_desktop_primary: "header_desktop_primary",
  header_desktop_panel: "header_desktop_panel",
  header_mobile_drawer: "header_mobile_drawer",
  header_mobile_accordion: "header_mobile_accordion",
  header_search_desktop: "header_search_desktop",
  header_search_mobile: "header_search_mobile",
  home_curated_section: "home_curated_section",
  home_curated_catalog_cta: "home_curated_catalog_cta",
  products_catalog: "products_catalog",
  landing_region: "landing_region",
  landing_theme: "landing_theme",
  consult_cta: "consult_cta",
  hero_search: "hero_search",
  quote_page: "quote_page",
  recommended_landing: "recommended_landing",
  deposit_page: "deposit_page",
  kakao_sync_auth: "kakao_sync_auth",
  home_hero: "home_hero",
  home_section: "home_section",
  home_promo_banner: "home_promo_banner",
  auth_modal: "auth_modal",
  mypage_membership: "mypage_membership",
  payment_return: "payment_return",
  planner: "planner",
} as const;
