import type { CSSProperties } from "react";

export type NotionThemeMode = "dark" | "light";

export const notionTokens = {
  typography: {
    fontFamily:
      '"Pretendard Variable","Pretendard","Inter",-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Noto Sans KR",sans-serif',
    baseSizeDesktop: "16px",
    baseSizeMobile: "15.5px",
    lineHeightBody: 1.7,
    lineHeightHeading: {
      h1: 1.25,
      h2: 1.3,
      h3: 1.35,
      h4: 1.35,
    },
    heading: {
      h1Size: "clamp(2rem, 2.6vw, 2.45rem)",
      h2Size: "clamp(1.64rem, 2.1vw, 2rem)",
      h3Size: "clamp(1.28rem, 1.65vw, 1.46rem)",
      h4Size: "clamp(1.12rem, 1.35vw, 1.22rem)",
      h1Weight: 720,
      h2Weight: 700,
      h3Weight: 650,
      h4Weight: 620,
    },
    quoteSize: "0.98rem",
    codeSize: "0.86em",
    captionSize: "0.78rem",
  },
  layout: {
    contentMaxWidth: "740px",
    imageMaxWidth: "780px",
    blockSpacingDesktop: "24px",
    blockSpacingMobile: "20px",
    h1Top: "28px",
    h1Bottom: "16px",
    h2Top: "44px",
    h2Bottom: "12px",
    h3Top: "32px",
    h3Bottom: "8px",
    paragraphBottom: "14px",
    headingSpacingTop: "34px",
    headingSpacingBottom: "14px",
    listIndent: "1.52rem",
    quotePadding: "10px 0 10px 16px",
    calloutPadding: "14px 16px",
    dividerMargin: "30px",
  },
  radius: {
    sm: "6px",
    md: "12px",
    lg: "14px",
  },
  shadow: {
    image: "0 1px 0 rgba(148, 163, 184, 0.08)",
  },
  colors: {
    dark: {
      textPrimary: "#E6EDF7",
      textSecondary: "#CAD5E6",
      textMuted: "#9AA8BF",
      heading: "#F7FAFF",
      link: "#9BC2FF",
      linkHover: "#BED8FF",
      underline: "rgba(155, 194, 255, 0.75)",
      codeText: "#EAF1FF",
      codeBg: "rgba(148, 163, 184, 0.2)",
      quoteBg: "rgba(30, 41, 59, 0.55)",
      quoteBorder: "rgba(148, 163, 184, 0.7)",
      calloutBg: "rgba(15, 23, 42, 0.58)",
      calloutBorder: "rgba(148, 163, 184, 0.34)",
      divider: "rgba(148, 163, 184, 0.32)",
      imageBg: "rgba(15, 23, 42, 0.42)",
    },
    light: {
      textPrimary: "#0F172A",
      textSecondary: "#1E293B",
      textMuted: "#64748B",
      heading: "#0B1220",
      link: "#1E5B8F",
      linkHover: "#1D4ED8",
      underline: "rgba(30, 58, 138, 0.62)",
      codeText: "#0F172A",
      codeBg: "rgba(15, 23, 42, 0.08)",
      quoteBg: "#F8FAFC",
      quoteBorder: "#CBD5E1",
      calloutBg: "#F8FAFC",
      calloutBorder: "#E2E8F0",
      divider: "#E2E8F0",
      imageBg: "#F8FAFC",
    },
  },
} as const;

type NotionVars = CSSProperties & Record<`--nt-${string}`, string>;

export function getNotionTokenVars(mode: NotionThemeMode = "dark"): NotionVars {
  const palette = notionTokens.colors[mode];
  return {
    "--nt-font-family": notionTokens.typography.fontFamily,
    "--nt-font-size-base": notionTokens.typography.baseSizeDesktop,
    "--nt-font-size-mobile": notionTokens.typography.baseSizeMobile,
    "--nt-line-height-body": String(notionTokens.typography.lineHeightBody),
    "--nt-h1-size": notionTokens.typography.heading.h1Size,
    "--nt-h2-size": notionTokens.typography.heading.h2Size,
    "--nt-h3-size": notionTokens.typography.heading.h3Size,
    "--nt-h4-size": notionTokens.typography.heading.h4Size,
    "--nt-h1-lh": String(notionTokens.typography.lineHeightHeading.h1),
    "--nt-h2-lh": String(notionTokens.typography.lineHeightHeading.h2),
    "--nt-h3-lh": String(notionTokens.typography.lineHeightHeading.h3),
    "--nt-h4-lh": String(notionTokens.typography.lineHeightHeading.h4),
    "--nt-h1-weight": String(notionTokens.typography.heading.h1Weight),
    "--nt-h2-weight": String(notionTokens.typography.heading.h2Weight),
    "--nt-h3-weight": String(notionTokens.typography.heading.h3Weight),
    "--nt-h4-weight": String(notionTokens.typography.heading.h4Weight),
    "--nt-quote-size": notionTokens.typography.quoteSize,
    "--nt-code-size": notionTokens.typography.codeSize,
    "--nt-caption-size": notionTokens.typography.captionSize,
    "--nt-content-max-width": notionTokens.layout.contentMaxWidth,
    "--nt-image-max-width": notionTokens.layout.imageMaxWidth,
    "--nt-block-spacing": notionTokens.layout.blockSpacingDesktop,
    "--nt-block-spacing-mobile": notionTokens.layout.blockSpacingMobile,
    "--nt-h1-top": notionTokens.layout.h1Top,
    "--nt-h1-bottom": notionTokens.layout.h1Bottom,
    "--nt-h2-top": notionTokens.layout.h2Top,
    "--nt-h2-bottom": notionTokens.layout.h2Bottom,
    "--nt-h3-top": notionTokens.layout.h3Top,
    "--nt-h3-bottom": notionTokens.layout.h3Bottom,
    "--nt-p-bottom": notionTokens.layout.paragraphBottom,
    "--nt-heading-top": notionTokens.layout.headingSpacingTop,
    "--nt-heading-bottom": notionTokens.layout.headingSpacingBottom,
    "--nt-list-indent": notionTokens.layout.listIndent,
    "--nt-quote-padding": notionTokens.layout.quotePadding,
    "--nt-callout-padding": notionTokens.layout.calloutPadding,
    "--nt-divider-margin": notionTokens.layout.dividerMargin,
    "--nt-radius-sm": notionTokens.radius.sm,
    "--nt-radius-md": notionTokens.radius.md,
    "--nt-radius-lg": notionTokens.radius.lg,
    "--nt-shadow-image": notionTokens.shadow.image,
    "--nt-text-primary": palette.textPrimary,
    "--nt-text-secondary": palette.textSecondary,
    "--nt-text-muted": palette.textMuted,
    "--nt-heading": palette.heading,
    "--nt-link": palette.link,
    "--nt-link-hover": palette.linkHover,
    "--nt-link-underline": palette.underline,
    "--nt-code-text": palette.codeText,
    "--nt-code-bg": palette.codeBg,
    "--nt-quote-bg": palette.quoteBg,
    "--nt-quote-border": palette.quoteBorder,
    "--nt-callout-bg": palette.calloutBg,
    "--nt-callout-border": palette.calloutBorder,
    "--nt-divider": palette.divider,
    "--nt-image-bg": palette.imageBg,
  };
}

