/** 유인물 복장·준비물 체크리스트 (날씨 연동, rule-based) */

export type FlyerOutfitChecklistItem = {
  text: string;
  /** false면 유인물 미리보기·인쇄에서 제외 */
  included: boolean;
};

export type FlyerOutfitDraftState = {
  items: FlyerOutfitChecklistItem[];
  summaryText: string;
  isAutoGenerated: boolean;
  /** UI 배지용 (hot | rain | sun | cold 등) */
  tags?: string[];
};

export const EMPTY_FLYER_OUTFIT_DRAFT: FlyerOutfitDraftState = {
  items: [],
  summaryText: "",
  isAutoGenerated: false,
  tags: [],
};
