import type { BandParsedProduct } from "@/lib/admin/bandImport/productParserSchema";

/** 테스트용 최소 BandParsedProduct (신규 필드 null 기본) */
export function minimalBandParsed(overrides: Partial<BandParsedProduct> = {}): BandParsedProduct {
  return {
    title: "제주 3박4일",
    description: "제주 여행 상품",
    band_marketing_copy: null,
    one_liner: null,
    price: 599000,
    duration: "3박4일",
    category: null,
    theme: "제주",
    overview_accommodation: null,
    overview_region: null,
    included_items: "항공+숙박",
    excluded_items: "개인경비",
    optional_expenses: null,
    optional_tours: null,
    booking_notes: null,
    options: null,
    status: "AVAILABLE",
    airline_name: null,
    departure_flight_number: "OZ8123",
    departure_from_airport: "김포",
    departure_to_airport: "제주",
    departure_from_date: null,
    departure_from_time: null,
    departure_to_date: null,
    departure_to_time: null,
    departure_baggage_limit: null,
    arrival_flight_number: "OZ8124",
    arrival_from_airport: "제주",
    arrival_to_airport: "김포",
    arrival_from_date: null,
    arrival_from_time: null,
    arrival_to_date: null,
    arrival_to_time: "10:20",
    arrival_baggage_limit: null,
    departure_time: "08:00",
    arrival_time: "09:10",
    seasonal_price_bands: {
      offSeason: "550000",
      weekend: "620000",
      peakSeason: 699000,
    },
    seasonal_price_band_notes: null,
    selling_points_json: null,
    detailed_schedule: null,
    travel_notes: null,
    booking_conditions: null,
    terms_and_notes: null,
    refund_policy: null,
    min_departure_people: null,
    meta_title: null,
    meta_description: null,
    point_benefits: null,
    point_tourism: null,
    point_guide: null,
    meeting_info: null,
    travel_insurance: null,
    departure_schedules: null,
    itinerary_v2_json: [
      {
        day: 1,
        title: "1일차",
        description: "제주 도착 후 렌트카 픽업",
        meals: { breakfast: null, lunch: "흑돼지", dinner: "해산물" },
      },
    ],
    theme_chart_json: null,
    ...overrides,
  };
}
